### ISSUE TITLE
Cannot share password with a user, even though he has a vault

### ISSUE THREAD

**Issue by b3nn0** [nextcloud/passman#318]
## Bug report
Hi,
With some users, I can share passwords, with one, however, I can't, even though the user does have a vault, a sharing key and also has passwords in the vault. We also tried to delete the vault and create a new one, but it doesn't help.
The user is suggessted when typing the username in the respective field. However, once it is clicked, the username just turns red:
![grafik](https://user-images.githubusercontent.com/1858945/27180150-39da7afa-51d2-11e7-987f-b64574909cc4.png)
![grafik](https://user-images.githubusercontent.com/1858945/27179790-7a5117da-51d0-11e7-8b58-113d89b30a00.png)

When sharing with other users that have a vault, it works fine.
When sharing with other users that don't have a vault, they are not even suggested.

### Steps to reproduce
1. Click on share
2. Type the username
3. Click on the username

### Expected behaviour
The username should be added to the list of users to be shared with

### Actual behaviour
The username simply turns red

### Configuration
**Operating system**:   Ubuntu 17.04

**Browser**:   Firefox 54, Chromium 58.0.3029.110

**Extensions that might cause interference**:   Adblock

**Passman version**:    2.1.2

**Operating system**: Ubuntu Server 16.04

**Web server:** Apache 2.4.18

**Database:** MySQL

**PHP version:** 7.0.18
      
**cloud server:** Nextcloud

**cloud version:** 12.0.0
  
   
#### Browser log
<details>
<summary>Browser log</summary>
```
Network log:
Only two request to "search", according to Chromium. No further request when clicking the username.

JS Log:
No output. Only "Crypto stuff initialized"
```
</details>   

#### Cloud log
None related to the issue.

**Comment by brantje** [comment]
Anything in the javascript console?

**Comment by animalillo** [comment]
Does the user has other vaults?
Did you have a pre-stable passman version before creating said user?
Is the user a nextcloud user or an ldap or some other auth mechanism?
Have you tried disabling adblock while using passman?

**Comment by b3nn0** [comment]
Javascript Console: Nope, nothing related to the issue.
Other vaults: No. We tried to delete the vault and recreate it multiple times, but it never worked.
Pre-stable version and user type:
Both users are Nextcloud users. They both existed in Owncloud for quite a long time and were migrated to nextcloud 10 or 11 I think. No special auth mechanism. I only started to use Passman about 2 months ago and never bothered with unstable versions I think. At least not that I don't remember doing so.

Disabling Adblock didn't help either.

I somehow have the feeling that it is related to the very short username (only 2 characters). Maybe there is some sanity check somewhere that checks $username.length() >= 3 or something?
Just a feeling though. Might be completely wrong.

**Comment by tripcreator** [comment]
same problem here:
sharing with other users works without problems just this one after selecting won´t get added to the
list (with the checkboxes)

Error: shareWith[z] is undefined
$scope.shareWith@https://x.x/apps/passman/js/passman.min.js?v=d45765c70c3075e276cf3d1229b859f7-19:31:15752
fn@https://x.x/apps/passman/js/passman.min.js?v=d45765c70c3075e276cf3d1229b859f7-19 line 6 > Function:4:479
b@https://x.x/apps/passman/js/passman.min.js?v=d45765c70c3075e276cf3d1229b859f7-19:4:29399
e@https://x.x/apps/passman/js/passman.min.js?v=d45765c70c3075e276cf3d1229b859f7-19:7:9952
$eval@https://x.x/apps/passman/js/passman.min.js?v=d45765c70c3075e276cf3d1229b859f7-19:5:7253
$apply@https://x.x/apps/passman/js/passman.min.js?v=d45765c70c3075e276cf3d1229b859f7-19:5:7485
compile/</<@https://x.x/apps/passman/js/passman.min.js?v=d45765c70c3075e276cf3d1229b859f7-19:7:10002
dispatch@https://x.x/core/vendor/core.js?v=d45765c70c3075e276cf3d1229b859f7-19:3:6414
add/r.handle@https://x.x/core/vendor/core.js?v=d45765c70c3075e276cf3d1229b859f7-19:3:3224

**Comment by brantje** [comment]
Should be fixed in latest version

**Comment by b3nn0** [comment]
Negative. I just upgraded and the issue still exists - can share with all users but the user "ko" as shown in the screenshots in the OP.
If there is any way I can assist further (e.g. adding some log commands to some files/lines or something like that), just let me know.

**Comment by animalillo** [comment]
can you check if he has the sharing keys generated on EVERY vault?
If so, try to create new ones of your desired strength.
And if the problem persists please let us know if you've got any errors on the server logs or on the browser console trough this process.

**Comment by b3nn0** [comment]
Alright, I regenerated all keys, but it didn't help. I tried to fetch as much log information as possible. If there is any way to make this more verbose, let me know.
Both users only have one vault.

# When generating new keys as the password owner:
In Apache log: nothing special, no errors. Only the usual http requests (censored - stripped IPs, user agent, guids):
```
"POST /index.php/apps/passman/api/v2/vaults/YYYYYYYY-YYYY-YYYY-YYYYYYYYYYYY/sharing-keys HTTP/1.1" 200 1049 "-" 
"POST /index.php/apps/passman/api/v2/vaults/YYYYYYYY-YYYY-YYYY-YYYY-YYYYYYYYYYYY/sharing-keys HTTP/1.1" 200 896 "-" 
```

In Browser console log (Chromium): nothing whatsoever
In the Nextcloud log:
A couple of errors, but it doesn't really look relevant:
```
Error	PHP	Method OC_L10N_String::__toString() must return a string value at /var/www/nextcloud/lib/private/L10N/L10N.php#85	2017-07-31T15:33:45+0200
Error	PHP	vsprintf(): Too few arguments at /var/www/nextcloud/lib/private/legacy/l10n/string.php#72	2017-07-31T15:33:45+0200
Error	PHP	Method OC_L10N_String::__toString() must return a string value at /var/www/nextcloud/lib/private/L10N/L10N.php#85	2017-07-31T15:28:49+0200
Error	PHP	vsprintf(): Too few arguments at /var/www/nextcloud/lib/private/legacy/l10n/string.php#72	2017-07-31T15:28:49+0200
```



# When generating new keys as the password receiver:
In the Browser log (Chromium) I can see this:
`core.js?v=640302e…-0:4 GET https://xxxxx/index.php/apps/passman/admin/delete-requests 403 (Forbidden)`
but only once. And it was not when regenerating they keys, but more like when opening the vault.
When generating the keys, nothing is shown in the log.
In Apache Log, no errors, just the access:
```
"POST /index.php/apps/passman/api/v2/vaults/XXXXXXXX-XXXX-XXXX-XXXX-XXXXXXXXXXXX/sharing-keys HTTP/1.1" 200 1105 "-"
"POST /index.php/apps/passman/api/v2/vaults/XXXXXXXX-XXXX-XXXX-XXXX-XXXXXXXXXXXX/sharing-keys HTTP/1.1" 200 952 "-"
```


# When typing in the share-user "ko" and clicking the suggestion:
In the browser console: nothing whatsoever
In the apache log: no errors
only some HTTP requests that succeed to:
```
"GET /index.php/apps/passman/api/v2/sharing/credential/XXXXXXXX-XXXX-XXXX-XXXX-XXXXXXXXXXXX/acl HTTP/1.1" 200 1047
"POST /index.php/apps/passman/api/v2/sharing/search HTTP/1.1" 200 989 
```
In nextcloud log:
Some more of this:
```
Error	PHP	Method OC_L10N_String::__toString() must return a string value at /var/www/nextcloud/lib/private/L10N/L10N.php#85	2017-07-31T15:40:13+0200
Error	PHP	vsprintf(): Too few arguments at /var/www/nextcloud/lib/private/legacy/l10n/string.php#72
```
