### ISSUE TITLE
Cannot export passwords

### ISSUE THREAD

**Issue by gjgd** [nextcloud/passman#532]
### Steps to reproduce
1. Go to Passman
2. Connect to vault
3. Settings
4. Export credentials
5. CSV
6. Enter password
7. Hit Export

### Expected behaviour
A file should start downloading

### Actual behaviour
Export is stuck at:
Starting export
Decrypting credentials

### Configuration
**Operating system**: 
MacOS Mojave 10.14.1

**Browser**:      
Tested on:
- Firefox: Quantum 64.0 (64-bit)
- Brave: Version 0.58.18 Chromium: 71.0.3578.98 (Official Build) (64-bit)
- Safari: Version 12.0.1 (14606.2.104.1.1) 

**Passman version**: 
Tested on:
- Passman 2.1.4
- Passman 2.2.1
      
**Cloud server:** Nextcloud or ownCloud
Tested on:
- NC 13
- NC 14
- NC 15

#### Note

- I tried [this fix](https://github.com/nextcloud/passman/wiki/Exporting%3Aa-single-users-credentials), but it didn't work
- I've seen those issues that seem related, but the proposed solution didn't help 
    - https://github.com/nextcloud/passman/issues/264
    - https://github.com/nextcloud/passman/issues/371
    - https://github.com/nextcloud/passman/issues/373
- The code I'm running includes this fix, but it doesn't seem to help: https://github.com/nextcloud/passman/pull/463/
- Seems to be related to https://github.com/nextcloud/passman/issues/454
#### Cloud log

<details>
<summary>Cloud log</summary>

```
{
  "reqId": "CENSORED",
  "level": 3,
  "time": "2018-12-24T16:22:46+00:00",
  "remoteAddr": "127.0.0.1",
  "user": "CENSORED",
  "app": "index",
  "method": "GET",
  "url": "\\/index.php\\/apps\\/passman\\/api\\/v2\\/file\\/undefined",
  "message": {
    "Exception": "OCP\\AppFramework\\Db\\DoesNotExistException",
    "Message": "Did expect one result but found none when executing: query \"SELECT * FROM `*PREFIX*passman_files` WHERE `id` = ? and `user_id` = ? \"; parameters Array\n(\n    [0] => undefined\n    [1] => CENSORED\n)\n; limit \"\"; offset \"\"",
    "Code": 0,
    "Trace": [
      {
        "file": "\\/snap\\/nextcloud\\/10255\\/htdocs\\/lib\\/public\\/AppFramework\\/Db\\/Mapper.php",
        "line": 372,
        "function": "findOneQuery",
        "class": "OCP\\AppFramework\\Db\\Mapper",
        "type": "->",
        "args": [
          "SELECT * FROM `*PREFIX*passman_files` WHERE `id` = ? and `user_id` = ? ",
          [
            "undefined",
            "CENSORED"
          ],
          null,
          null
        ]
      },
      {
        "file": "\\/var\\/snap\\/nextcloud\\/10255\\/nextcloud\\/extra-apps\\/passman\\/lib\\/Db\\/FileMapper.php",
        "line": 55,
        "function": "findEntity",
        "class": "OCP\\AppFramework\\Db\\Mapper",
        "type": "->",
        "args": [
          "SELECT * FROM `*PREFIX*passman_files` WHERE `id` = ? and `user_id` = ? ",
          [
            "undefined",
            "CENSORED"
          ]
        ]
      },
      {
        "file": "\\/var\\/snap\\/nextcloud\\/10255\\/nextcloud\\/extra-apps\\/passman\\/lib\\/Service\\/FileService.php",
        "line": 53,
        "function": "getFile",
        "class": "OCA\\Passman\\Db\\FileMapper",
        "type": "->",
        "args": [
          "undefined",
          "CENSORED"
        ]
      },
      {
        "file": "\\/var\\/snap\\/nextcloud\\/10255\\/nextcloud\\/extra-apps\\/passman\\/controller\\/filecontroller.php",
        "line": 58,
        "function": "getFile",
        "class": "OCA\\Passman\\Service\\FileService",
        "type": "->",
        "args": [
          "undefined",
          "CENSORED"
        ]
      },
      {
        "file": "\\/snap\\/nextcloud\\/10255\\/htdocs\\/lib\\/private\\/AppFramework\\/Http\\/Dispatcher.php",
        "line": 166,
        "function": "getFile",
        "class": "OCA\\Passman\\Controller\\FileController",
        "type": "->",
        "args": [
          "undefined"
        ]
      },
      {
        "file": "\\/snap\\/nextcloud\\/10255\\/htdocs\\/lib\\/private\\/AppFramework\\/Http\\/Dispatcher.php",
        "line": 99,
        "function": "executeController",
        "class": "OC\\AppFramework\\Http\\Dispatcher",
        "type": "->",
        "args": [
          {
            "__class__": "OCA\\Passman\\Controller\\FileController"
          },
          "getFile"
        ]
      },
      {
        "file": "\\/snap\\/nextcloud\\/10255\\/htdocs\\/lib\\/private\\/AppFramework\\/App.php",
        "line": 118,
        "function": "dispatch",
        "class": "OC\\AppFramework\\Http\\Dispatcher",
        "type": "->",
        "args": [
          {
            "__class__": "OCA\\Passman\\Controller\\FileController"
          },
          "getFile"
        ]
      },
      {
        "file": "\\/snap\\/nextcloud\\/10255\\/htdocs\\/lib\\/private\\/AppFramework\\/Routing\\/RouteActionHandler.php",
        "line": 47,
        "function": "main",
        "class": "OC\\AppFramework\\App",
        "type": "::",
        "args": [
          "OCA\\Passman\\Controller\\FileController",
          "getFile",
          {
            "__class__": "OC\\AppFramework\\DependencyInjection\\DIContainer"
          },
          {
            "file_id": "undefined",
            "_route": "passman.file.getFile"
          }
        ]
      },
      {
        "function": "__invoke",
        "class": "OC\\AppFramework\\Routing\\RouteActionHandler",
        "type": "->",
        "args": [
          {
            "file_id": "undefined",
            "_route": "passman.file.getFile"
          }
        ]
      },
      {
        "file": "\\/snap\\/nextcloud\\/10255\\/htdocs\\/lib\\/private\\/Route\\/Router.php",
        "line": 297,
        "function": "call_user_func",
        "args": [
          {
            "__class__": "OC\\AppFramework\\Routing\\RouteActionHandler"
          },
          {
            "file_id": "undefined",
            "_route": "passman.file.getFile"
          }
        ]
      },
      {
        "file": "\\/snap\\/nextcloud\\/10255\\/htdocs\\/lib\\/base.php",
        "line": 987,
        "function": "match",
        "class": "OC\\Route\\Router",
        "type": "->",
        "args": [
          "\\/apps\\/passman\\/api\\/v2\\/file\\/undefined"
        ]
      },
      {
        "file": "\\/snap\\/nextcloud\\/10255\\/htdocs\\/index.php",
        "line": 42,
        "function": "handleRequest",
        "class": "OC",
        "type": "::",
        "args": []
      }
    ],
    "File": "\\/snap\\/nextcloud\\/10255\\/htdocs\\/lib\\/public\\/AppFramework\\/Db\\/Mapper.php",
    "Line": 284,
    "CustomMessage": "--"
  },
  "userAgent": "Mozilla\\/5.0 (Macintosh; Intel Mac OS X 10_14_1) AppleWebKit\\/605.1.15 (KHTML, like Gecko) Version\\/12.0.1 Safari\\/605.1.15",
  "version": "15.0.0.10"
}```
</details>

**Comment by IBBoard** [comment]
I just hit this. It looks like I tried the fix before (because I had an entry called "ZZZ_Credentials" with a dummy.txt file.

In the console output I saw:
```
Error: _credential[field] is null
PassmanExporter.csv.export/</<@https://pim.ibboard.co.uk/apps/passman/js/passman.min.js?v=b6c45afe-25:29:30003
C_Promise/this.call_then@https://pim.ibboard.co.uk/apps/passman/js/passman.min.js?v=b6c45afe-25:2:31989
getCredentialsWithFiles/</this.parent.step<@https://pim.ibboard.co.uk/apps/passman/js/passman.min.js?v=b6c45afe-25:29:28385
getCredentialsWithFiles/</<@https://pim.ibboard.co.uk/apps/passman/js/passman.min.js?v=b6c45afe-25:29:28964
e/<@https://pim.ibboard.co.uk/apps/passman/js/passman.min.js?v=b6c45afe-25:4:31818
$eval@https://pim.ibboard.co.uk/apps/passman/js/passman.min.js?v=b6c45afe-25:5:7253
$digest@https://pim.ibboard.co.uk/apps/passman/js/passman.min.js?v=b6c45afe-25:5:5797
$apply@https://pim.ibboard.co.uk/apps/passman/js/passman.min.js?v=b6c45afe-25:5:7549
l@https://pim.ibboard.co.uk/apps/passman/js/passman.min.js?v=b6c45afe-25:4:14916
J@https://pim.ibboard.co.uk/apps/passman/js/passman.min.js?v=b6c45afe-25:4:17136
gg/</t.onload@https://pim.ibboard.co.uk/apps/passman/js/passman.min.js?v=b6c45afe-25:4:17610
 passman.min.js:4:25218
	e https://pim.ibboard.co.uk/apps/passman/js/passman.min.js?v=b6c45afe-25:4
	get https://pim.ibboard.co.uk/apps/passman/js/passman.min.js?v=b6c45afe-25:4
	e https://pim.ibboard.co.uk/apps/passman/js/passman.min.js?v=b6c45afe-25:4
	eval https://pim.ibboard.co.uk/apps/passman/js/passman.min.js?v=b6c45afe-25:5
	digest https://pim.ibboard.co.uk/apps/passman/js/passman.min.js?v=b6c45afe-25:5
	apply https://pim.ibboard.co.uk/apps/passman/js/passman.min.js?v=b6c45afe-25:5
	l https://pim.ibboard.co.uk/apps/passman/js/passman.min.js?v=b6c45afe-25:4
	J https://pim.ibboard.co.uk/apps/passman/js/passman.min.js?v=b6c45afe-25:4
	onload https://pim.ibboard.co.uk/apps/passman/js/passman.min.js?v=b6c45afe-25:4
```

Exporting as JSON worked fine.

**Comment by alnixon** [comment]
I've made a pull request for my fix metioned above.
Attached to this comment is my copy of passman.min.js that can be used while this request is being processed (since making the request I've noticed there was already Pull Request #264 that would have addressed this, pending since Jan 30th 2019)

[passman.min.js.txt](https://github.com/nextcloud/passman/files/3097968/passman.min.js.txt)

**Comment by newhinton** [comment]
Fixed with #573

**Comment by Linuxine** [comment]
Hi, I have just installed version  2.2.24, and now I cannot export my credentials at all, when opening a vault the page is not complete (tested on Firefox 66 and Vivaldi): I do not have the "settings" menu in the passwords page any more, there is nothing at the left of the page, where were the "settings", "donate" and "logout" menu.

The web console indicates :
```
Error: JSON.parse: unexpected character at line 1 column 1 of the JSON data
getSearchFieldArraySettings@/apps/passman/js/passman.min.js?v=10b10fe7-0:28:11788
expandSearch@/apps/passman/js/passman.min.js?v=10b10fe7-0:28:15216
@cloud/apps/passman/js/passman.min.js?v=10b10fe7-0:31:15647
invoke@/apps/passman/js/passman.min.js?v=10b10fe7-0:3:18540
ff/this.$get</</<@/apps/passman/js/passman.min.js?v=10b10fe7-0:4:10933
p@apps/passman/js/passman.min.js?v=10b10fe7-0:3:30388
g@apps/passman/js/passman.min.js?v=10b10fe7-0:3:27212
aa/<@apps/passman/js/passman.min.js?v=10b10fe7-0:3:26857
ac/<@/apps/passman/js/passman.min.js?v=10b10fe7-0:3:29287
d@apps/passman/js/passman.min.js?v=10b10fe7-0:3:27707
m@apps/passman/js/passman.min.js?v=10b10fe7-0:3:29737
link/<@apps/passman/js/passman.min.js?v=10b10fe7-0:7:10226
$digest@/apps/passman/js/passman.min.js?v=10b10fe7-0:5:6102
$apply@apps/passman/js/passman.min.js?v=10b10fe7-0:5:7549
@apps/passman/js/passman.min.js?v=10b10fe7-0:29:4986
dispatch@core/js/dist/main.js?v=10b10fe7-0:39:34029
add/_.handle@core/js/dist/main.js?v=10b10fe7-0:39:30848
passman.min.js:4:25218
    e passman.min.js:4
    get passman.min.js:4
    $digest passman.min.js:5
    $apply passman.min.js:5
    <anonymous> passman.min.js:29
    jQuery 2
Deprecated call $.tooltip('fixTitle') has been deprecated and should be removed tooltip.js:32:4
```

I have missed something ? A cache or minification issue ?

**Comment by newhinton** [comment]
This is a known bug that we detected earlier.
See #578 for more details

**Comment by newhinton** [comment]
Please have a little patience while we create a proper fix for this bug

**Comment by Linuxine** [comment]
Oki, thanks ! :)

**Comment by gjgd** [comment]
Thanks @newhinton for being on top of this! Reopening for now, I got the same issue as @Linuxine

**Comment by Linuxine** [comment]
Hi, I have just installed the 2.3 version and the sidebar is back, thanks ! :)
Just for information (no pressure here, I will wait until this is fixed), the export is still not working, still stuck on the "decrypting credential part", on Firefox and Vivaldi.

**Comment by newhinton** [comment]
@Linuxine
I can not reproduce your error. The latest version finishes the export on 3 different systems. can you provide more information, maybe javascript logs?

**Comment by Linuxine** [comment]
Hi @newhinton, I have no js error, but in the nextcloud.log, it seems that the extract request has an issue ? When trying to export, I get a lot of logs like this one, maybe once by credential to be exported (I have redacted my Ip and username with "xxx")
 ```
"reqId":"XNqC5UCK4yuTe15LVzHGZgAAAAs","level":3,"time":"2019-05-14T08:57:10+00:00","remoteAddr":"x.x.x.x","user":"xxx","app":"index","method":"GET","url":"\/cloud\/index.php\/apps\/passman\/api\/v2\/file\/undefined",
"message":{"Exception":"OCP\\AppFramework\\Db\\DoesNotExistException","Message":"Did expect one result but found none when executing: query \"SELECT * FROM `*PREFIX*passman_files` WHERE `id` = ? and `user_id` = ? \"; parameters Array\n(\n    [0] => undefined\n    [1] => xxx\n)\n; limit \"\"; offset \"\"","Code":0,"Trace":[
{"file":"\/var\/www\/nextcloud\/lib\/public\/AppFramework\/Db\/Mapper.php","line":372,"function":"findOneQuery","class":"OCP\\AppFramework\\Db\\Mapper","type":"->","args":["SELECT * FROM `*PREFIX*passman_files` WHERE `id` = ? and `user_id` = ? ",["undefined","xxx"],null,null]},
{"file":"\/var\/www\/nextcloud\/apps\/passman\/lib\/Db\/FileMapper.php","line":55,"function":"findEntity","class":"OCP\\AppFramework\\Db\\Mapper","type":"->","args":["SELECT * FROM `*PREFIX*passman_files` WHERE `id` = ? and `user_id` = ? ",["undefined","xxx"]]},
{"file":"\/var\/www\/nextcloud\/apps\/passman\/lib\/Service\/FileService.php","line":53,"function":"getFile","class":"OCA\\Passman\\Db\\FileMapper","type":"->","args":["undefined","xxx"]},
{"file":"\/var\/www\/nextcloud\/apps\/passman\/controller\/filecontroller.php","line":58,"function":"getFile","class":"OCA\\Passman\\Service\\FileService","type":"->","args":["undefined","xxx"]},
{"file":"\/var\/www\/nextcloud\/lib\/private\/AppFramework\/Http\/Dispatcher.php","line":166,"function":"getFile","class":"OCA\\Passman\\Controller\\FileController","type":"->","args":["undefined"]},
{"file":"\/var\/www\/nextcloud\/lib\/private\/AppFramework\/Http\/Dispatcher.php","line":99,"function":"executeController","class":"OC\\AppFramework\\Http\\Dispatcher","type":"->","args":[{"__class__":"OCA\\Passman\\Controller\\FileController"},"getFile"]},{"file":"\/var\/www\/linuxine\/nextcloud\/lib\/private\/AppFramework\/App.php","line":126,"function":"dispatch","class":"OC\\AppFramework\\Http\\Dispatcher","type":"->","args":[{"__class__":"OCA\\Passman\\Controller\\FileController"},"getFile"]},
{"file":"\/var\/www\/nextcloud\/lib\/private\/AppFramework\/Routing\/RouteActionHandler.php","line":47,"function":"main","class":"OC\\AppFramework\\App","type":"::","args":["OCA\\Passman\\Controller\\FileController","getFile",{"__class__":"OC\\AppFramework\\DependencyInjection\\DIContainer"},{"file_id":"undefined","_route":"passman.file.getFile"}]},{"function":"__invoke","class":"OC\\AppFramework\\Routing\\RouteActionHandler","type":"->","args":[{"file_id":"undefined","_route":"passman.file.getFile"}]},
{"file":"\/var\/www\/nextcloud\/lib\/private\/Route\/Router.php","line":297,"function":"call_user_func","args":[{"__class__":"OC\\AppFramework\\Routing\\RouteActionHandler"},
{"file_id":"undefined","_route":"passman.file.getFile"}]},
{"file":"\/var\/www\/nextcloud\/lib\/base.php","line":975,"function":"match","class":"OC\\Route\\Router","type":"->","args":["\/apps\/passman\/api\/v2\/file\/undefined"]},
{"file":"\/var\/www\/nextcloud\/index.php","line":42,"function":"handleRequest","class":"OC","type":"::","args":[]}],"File":"\/var\/www\/nextcloud\/lib\/public\/AppFramework\/Db\/Mapper.php","Line":284,"CustomMessage":"--"},"userAgent":"Mozilla\/5.0 (X11; Fedora; Linux x86_64; rv:66.0) Gecko\/20100101 Firefox\/66.0","version":"16.0.0.9"}
```

**Comment by Linuxine** [comment]
Note, I have a vault with 6 credential, and the export is working. The export is failing on my main vault, which contains 108 credentials. I am not sure this is related, but it seems that with the update there is something wrong in this vault now, when trying to update a credential, I get this in the logs:

```
"Exception":"Doctrine\\DBAL\\Exception\\DriverException","Message":"An exception occurred while executing 'UPDATE `oc_passman_credentials` [...] Syntax error or access violation: 1118 Row size too large (> 8126). Changing some columns to TEXT or BLOB or using ROW_FORMAT=DYNAMIC or ROW_FORMAT=COMPRESSED may help. In current row format, BLOB prefix of 768 bytes is stored inline.",{"errorInfo":["42000",1118,"Row size too large (> 8126). Changing some columns to TEXT or BLOB or using ROW_FORMAT=DYNAMIC or ROW_FORMAT=COMPRESSED may help. In current row format, BLOB prefix of 768 bytes is stored inline."
```

**Comment by newhinton** [comment]
can you open a seperate issue for that?

**Comment by newhinton** [comment]
since the issue with the exporter is fixed, and the problem you are describing is not based in the exportprocess, i am closing this issue. Please create new issue for your problem :)

**Comment by Linuxine** [comment]
I was able to edit my credentials by deleting the icon associated to it (I did not ask for this icon to be fetch, but this is something that could be disabled it seems). I have edited all my 108 credentials to remove the icon, and now I can edit them again. But the export is still not working for my vault, still the same symptoms :/

**Comment by Linuxine** [comment]
I don't get why when exporting the vault, the request contains so many undefined, is it normal ?
```
"method":"GET","url":"\/cloud\/index.php\/apps\/passman\/api\/v2\/file\/undefined","message":{"Exception":"OCP\\AppFramework\\Db\\DoesNotExistException","Message":"Did expect one result but found none when executing: query \"SELECT * FROM `*PREFIX*passman_files` WHERE `id` = ? and `user_id` = ? \"; parameters Array\n(\n    [0] => undefined\n    [1] => aline\n)\n; limit \"\"; offset \"\"","Code":0,"Trace":[{"file":"\/var\/www\/linuxine\/nextcloud\/lib\/public\/AppFramework\/Db\/Mapper.php","line":372,"function":"findOneQuery","class":"OCP\\AppFramework\\Db\\Mapper","type":"->","args":["SELECT * FROM `*PREFIX*passman_files` WHERE `id` = ? and `user_id` = ? ",["undefined","user"],null,null]},
```
there is an "undefined" in the get url, and also for the "id" in the query, that should explain why the query return no result...

**Comment by Linuxine** [comment]
Okay, I fixed it ! I appears one of my deleted credentials had very huge values (very very long string, I guess the Firefox plugin had bugued when saving the credentials) and this was making the export fail. After deleting them, I am able to export my credentials again ! \o/

Maybe it would be nice to be able to choose if whether or not we want to export the deleted credentials ?
Anyway, thanks for the help, and for having fixed the export ! :)

**Comment by gjgd** [comment]
I tried your fix @Linuxine and have upgraded to 2.3.0 but still get this error in the JS console when trying to export:
```
Error: data.replaceAll is not a function
```

Any idea @newhinton?

I'm on Nextcloud 15.07

**Comment by benedikt-buchert** [comment]
I'm getting the error `ccm: tag doesn't match` in the js console with Nextcloud 18
`corrupt {message: "ccm: tag doesn't match", toString: ƒ}`

**Comment by Mte90** [comment]
I used that to export everything https://github.com/nextcloud/passman/issues/264#issuecomment-459079310 but yes doesn't work on my instance

**Comment by binsky08** [comment]
is this still an issue with the current passman version?

**Comment by benedikt-buchert** [comment]
For me ist still does not work.But I guess this can have several reasons.

**Comment by binsky08** [comment]
Is it still that `ccm: tag doesn't match` error?

**Comment by benedikt-buchert** [comment]
Yes

**Comment by Linuxine** [comment]
Hi,

for me the csv export in working, with Firefox 91, on Nextcloud 21.0.4 and Passman 2.3.8.
