### ISSUE TITLE
Import from LastPass or KeePass impossible

### ISSUE THREAD

**Issue by nuxlight** [nextcloud/passman#589]
### Steps to reproduce
1. Generate Keepas CSV file
2. Go to Import section in Passman parameters
3. Select Keepass import type
4. Start import

### Expected behaviour
All my password will be added in my Passman account

### Actual behaviour
No import and error in javascript console

### Configuration

**Browser**: Chromium 74.0.3729.131       

**Extensions that might cause interference**:   

**Passman version**:    2.3.0

**Operating system**: Windows 10

**Web server:** Apache (Nextcloud-Docker)

**Database:** MariaDB

**PHP version:**
      
**cloud server:** Nextcloud

**cloud version:** 16.0.0
  
   
#### Browser log
<details>
passman.min.js?v=806176c8-0:10 Uncaught TypeError: Cannot read property 'slice' of undefined
    at Object.encrypt (passman.min.js?v=806176c8-0:10)
    at Object.encrypt (passman.min.js?v=806176c8-0:11)
    at Object.encryptString (passman.min.js?v=806176c8-0:28)
    at Object.createCredential (passman.min.js?v=806176c8-0:28)
    at addCredential (passman.min.js?v=806176c8-0:31)
    at C_Promise.finally (passman.min.js?v=806176c8-0:31)
    at C_Promise.call_then (passman.min.js?v=806176c8-0:2)
    at C_Promise.<anonymous> (passman.min.js?v=806176c8-0:29)
encrypt @ passman.min.js?v=806176c8-0:10
encrypt @ passman.min.js?v=806176c8-0:11
encryptString @ passman.min.js?v=806176c8-0:28
createCredential @ passman.min.js?v=806176c8-0:28
addCredential @ passman.min.js?v=806176c8-0:31
(anonymous) @ passman.min.js?v=806176c8-0:31
C_Promise.call_then @ passman.min.js?v=806176c8-0:2
(anonymous) @ passman.min.js?v=806176c8-0:29
setTimeout (async)
C_Promise @ passman.min.js?v=806176c8-0:3
PassmanImporter.keepassCsv.readFile @ passman.min.js?v=806176c8-0:29
$scope.startImport @ passman.min.js?v=806176c8-0:31
(anonymous) @ passman.min.js?v=806176c8-0:6
b @ passman.min.js?v=806176c8-0:4
e @ passman.min.js?v=806176c8-0:7
$eval @ passman.min.js?v=806176c8-0:5
$apply @ passman.min.js?v=806176c8-0:5
(anonymous) @ passman.min.js?v=806176c8-0:7
dispatch @ main.js?v=806176c8-0:39
_.handle @ main.js?v=806176c8-0:39
</details>

**Comment by Fiodin** [comment]
same here with 
Configuration
Browser: Opera and Firefox

Therefore I tried it with a generic csv import and it is the same behaviour.

**Comment by Fiodin** [comment]
in the meantime I tried something different:
### **Steps to reproduce**
1. Generate Passman JSON file
2. Go to Import section in Passman parameters
3. Select Passman JSON import type
4. Start import.

### **Expected behaviour**
All my password will be added in my Passman account

### **Actual behaviour**
No import and it stucks at one password less than the sum is: e.g.: 255/256 or 267/268
It does not matter how many passwords are imported. For the same file it is always the same password. If the password is deleted from Passman and re-exported, it is a different password.

### **Configuration**
**Browser**: see above

Extensions that might cause interference:

Passman version: 2.3.0

Operating system: Debian stretch

Web server: Apache 2.4

Database: MariaDB 10.1

PHP version: 7.2

cloud server: Nextcloud

cloud version: 16.0.0.9

**Comment by joergmschulz** [comment]
import also impossible from passman/json. While all entries are read, the import stops after the first step ('Datei gelesen'). Using postgres, same effect on a server using mariadb.
Console shows the following errors (chrome)

```
Uncaught TypeError: Cannot read property 'slice' of undefined
    at Object.encrypt (passman.min.js?v=207d66c1-11:10)
    at Object.encrypt (passman.min.js?v=207d66c1-11:11)
    at Object.encryptString (passman.min.js?v=207d66c1-11:28)
    at Object.createCredential (passman.min.js?v=207d66c1-11:28)
    at addCredential (passman.min.js?v=207d66c1-11:31)
    at C_Promise.finally (passman.min.js?v=207d66c1-11:31)
    at C_Promise.call_then (passman.min.js?v=207d66c1-11:2)
    at C_Promise.<anonymous> (passman.min.js?v=207d66c1-11:29)
```

Firefox shows at the same step:
```
Uncaught TypeError: Cannot read property 'slice' of undefined
    at Object.encrypt (passman.min.js?v=207d66c1-11:10)
    at Object.encrypt (passman.min.js?v=207d66c1-11:11)
    at Object.encryptString (passman.min.js?v=207d66c1-11:28)
    at Object.createCredential (passman.min.js?v=207d66c1-11:28)
    at addCredential (passman.min.js?v=207d66c1-11:31)
    at C_Promise.finally (passman.min.js?v=207d66c1-11:31)
    at C_Promise.call_then (passman.min.js?v=207d66c1-11:2)
    at C_Promise.<anonymous> (passman.min.js?v=207d66c1-11:29)
```

**Comment by JazMTaz** [comment]
Same issue for me importing Lastpass CSV (Linux Lubuntu 16.04 Nginx MariaDB PHP7.1). Freezes at one less than total password count 297/298. Browser Chromium Version 73.0.3683.103 (Official Build) (64-bit) and also attempted with Firefox Quantum 66.0.5 (64-bit).

**Comment by JazMTaz** [comment]
Passman version 2.3.1 still having the same issue.

**Comment by nuxlight** [comment]
Same behavior with CSV file

![image](https://user-images.githubusercontent.com/2751135/58163854-ff2a4b80-7c84-11e9-80bd-f843cd777b75.png)

Maybe this is due to Newtcloud version and Docker ?

**Comment by Fiodin** [comment]
Mine is not a Docker-Version and I just updated to
**cloud server:** Nextcloud
**cloud version:** 16.0.1
**Passman version:** 2.3.1
Still got the same problems from above.

**Comment by JazMTaz** [comment]
My setup is also not using docker

Passman version 2.3.1 has the same issue for me importing Lastpass CSV on Nextcloud 16.0.1 (Linux Lubuntu 16.04 Nginx MariaDB PHP7.1). Freezes at one less than total password count 297/298. Browser Chromium Version 74.0.3729.169 (Official Build) (64-bit) and also attempted with Firefox Quantum 66.0.5 (64-bit).

**Comment by digitalfox** [comment]
I reproduce the issue with nextcloud 15.0.8 on Debian GNU/Linux 9 and passman 2.3.1 while importing generic csv.

**Comment by bertrand-benoit** [comment]
I have the same issue too, hosted on Gandi (French Hoster), Nextcloud 16 and passman 2.3.1; while either importing with KeePass importer or generic one.

**Comment by wheeler01** [comment]
Exact same behavior on 16 for me.

**Comment by Oliv4945** [comment]
For all people having issues, could you please attach a sample failing CSV file ? I do not have Lastlane and so on.

For Keepass users: Are you using Keepass or KeepassXC ?  If Keepass are you using [those options](http://i.imgur.com/CaeTA4d.png) ?

**Comment by nuxlight** [comment]
I create a CSV file with KeePass (version 2.42.1) I have the error with this file.
[Database.zip](https://github.com/nextcloud/passman/files/3252036/Database.zip)

**Comment by wheeler01** [comment]
[kp.zip](https://github.com/nextcloud/passman/files/3252246/kp.zip)

I use Linux. I installed Keepass to import my Google Chrome passwords, since Generic CSV fails to import right now too. I wanted to import the Chrome CSV into Keepass. Then export Keepass and try to import that into Passman.

When that failed, I decided to try with the Keepass example data. That failed to import into Passman as well. However, I have included the example data in the attached ZIP  file. As well a screencast of the exact steps taken to create it.

I am confused because we are not given an opportunity to select the options in the image provided by  @Oliv4945 earlier.

I am excited to begin using Passman. I hope the info I have provided here helps.

**Comment by Oliv4945** [comment]
Fixed. All imports where broken, should be better know. Thank you for your files.

> I am confused because we are not given an opportunity to select the options in the image provided by @Oliv4945 earlier.

It seems that KeePass has no options anymore, I updated the documentation

**Comment by wheeler01** [comment]
Of course I can't speak for everybody but, as for me, still the same issue (both generic and Keepass). I even cloned github again, just in case... Is there more info I can provide?

**Comment by mrbluesky125** [comment]
I hacked the fix in the already installed app (passman.min.js, search for 'otp:{},hidden:!1) and imported a 600 lines file, with the generic importer.

**Comment by Oliv4945** [comment]
Did you clone the right branch ?

**Comment by wheeler01** [comment]
Um... Which one?

**Comment by Oliv4945** [comment]
> Um... Which one?

https://github.com/Oliv4945/passman/commits/fix/589/ImportIssues , it is not merge in Passman yet

**Comment by wheeler01** [comment]
Got it! Thanks! :) I can confirm, generic CSV import is working.

**Comment by JazMTaz** [comment]
I can confirm that the import of Lastpass .csv also worked normally

**Comment by addrian1** [comment]
It also hangs on the last value, but if I restart the safe, I see a successful import.
