### ISSUE TITLE
Files not downloadable

### ISSUE THREAD

**Issue by Luticus** [nextcloud/passman#732]
### Steps to reproduce
1. try to download file from passman

### Expected behaviour
When you click a file from the sidebar, it should download

### Actual behaviour
Nothing, This error can be seen in the console:
Error: escapeHTML is not defined

### Configuration
**Operating system**:   
Debian 11

**Browser**:      
Firefox 93
Chromium 90

**Extensions that might cause interference**:   Tested in clean browser with no extensions

**Passman version**:    
2.3.7

**Operating system**: 
Debian 11

**Web server:** 
Apache 2.4

**Database:** 
MariaDB

**PHP version:** 
7.3
      
**cloud server:** 
Nextcloud

**cloud version:** (see admin page or version.php)
22.2.0
  
   
#### Browser log
<details>
<summary>Browser log</summary>
```
Error: escapeHTML is not defined
```
</details>

**Comment by binsky08** [comment]
This bug should already be fixed.

You need to update to the latest Passman version.
This requires at least PHP 7.4.

**Comment by Luticus** [comment]
Ok, will do, thanks!

**Comment by Luticus** [comment]
Just upgraded system to Debian Bullseye which put me on php7.4 and I can confirm I'm still seeing this issue. Same error message and everything.

**Comment by Luticus** [comment]
I'll check my passman version and see if I can update it.

**Comment by Luticus** [comment]
Yep, confirmed working in the latest version. For some reason new versions of passman weren't being offered by the app store in nextcloud, had to manually grab it from apps.nextcloud.com, so I wasn't even aware I was on an older version.

Thanks for the help!
